package jogo.abstracts;

/**
 *
 * @author José Gustavo
 */
public enum Local {
    MEIO_SUPERIOR, MEIO_INFERIOR, CANTO_SUPERIOR_DIREITO, CANTO_SUPERIOR_ESQUERDO, MEIO_ESQUERDO, MEIO,
    MEIO_DIREITO, CANTO_INFERIOR_ESQUERDO, CANTO_INFERIOR_DIREITO
}
